name: "Post test results to slack"
description: "Upload pictures taken during test run to slack channel"
inputs:
  slack-token:
    description: "Slack token"
    required: true
    default: "123"
  picture-path:
    description: "Folder path with pictures to upload"
    required: true
    default: "cypress/screenshots"
  channels:
    description: "Comma separated list of channels to post in"
    required: true
    default: "channel1, channel2"
outputs:
  message:
    description: "Reply from slack"
runs:
  using: "node12"
  main: "dist/index.js"
